spring:
# These properties are set using environment variables during the `docker create` step
#  datasource:
#    # Use `localhost` instead of using the Docker network name when running a local PostgreSQL instance.
#    url: 'jdbc:postgresql://docker-network:5432/dbname'
#    username: 'springuser'
#    password: 'SuperSecret'
  liquibase:
    change-log: classpath:db/changelog-main.xml
  jpa:
    hibernate:
      # Don't create/modify databases by inferring its properties from the models.
      ddl-auto: 'none'
    # See: https://stackoverflow.com/a/48222934/10620237
    open-in-view: false

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
