version: '3.8'

networks:
  renameme-network:
    driver: bridge

services:
  renameme-database:
    container_name: renameme-database
    image: postgres
    networks:
      - renameme-network
    ports:
      - 5432:5432
    env_file: ./postgres-envars.list

  renameme:
    container_name: renameme
    image: renameme
    build:
      context: ../
      cache_from:
        - ${GRADLE_IMAGE:-renameme-gradle_container}
        - ${MAIN_IMAGE:-renameme}
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:8000
      - 8080:8080
    networks:
      - renameme-network
    links:
      - renameme-database
    depends_on:
      - renameme-database
