FROM gradle:7.2-jdk11

RUN mkdir -p /home/gradle/project/src/main
COPY ggbot/build.gradle /home/gradle/project
COPY ggbot/src/main /home/gradle/project/src/main

WORKDIR /home/gradle/project
RUN chown gradle:gradle --recursive .

USER gradle
