binPath: './bin'

docker:
  # Docker base directory path, relative to this Gradle subproject.
  baseDirPath: '..'
  # Dockerfile directory path, relative to this Gradle subproject.
  dockerfileGradlePath: '../docker/Dockerfile-gradle'
  network: ggbot-network
  testNetwork: ggbot-test-network

  buildImage:
    name: ggbot-gradle-build
    user: gradle
    volume: gradle-build-cache
    # Location of Gradle cache inside the Docker container.
    gradleCachePath: '/home/gradle/.gradle'
    libsPath: '/home/gradle/project/build/libs'
    libsArchiveName: 'build-image-libs.tar.gz'
    command:
      - gradle
      - build
      - --stacktrace
      - --exclude-task
      - test

  mainImage:
    name: ggbot
    port: '8080'
    debugPort: '8000'

  databaseContainer:
    repoTag: postgres:latest
    name: ggbot-database
    port: '5432'

  databaseTestContainer:
    repoTag: postgres:latest
    name: ggbot-test-database
    port: '5444'

  pgAdminContainer:
    repoTag: dpage/pgadmin4
    name: pgadmin
    port: '5050'
