name: Unit and Integration Tests

on:
  push:
    paths:
      - '.github/workflows/unit-and-integration-tests.yml'
      - 'bin/**'
      - '!bin/api_tests.py'
      - '!bin/pgadmin.py'
      - '!bin/run.py'
      - 'src/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'settings.gradle'

env:
  GRADLE_CACHE: 'cache-gradle'
  TMP_CACHE: 'cache-tmp'
  PYENV_PATH: '/opt/hostedtoolcache/pyenv_root'
  PYTHON_VERSION: '3.9.0'

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ env.GRADLE_CACHE }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.GRADLE_CACHE }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64

      - name: Grant Gradle wrapper (gradlew) sufficient permissions
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew build --info

      - name: Run unit tests
        run: ./gradlew test --info

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ env.GRADLE_CACHE }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.GRADLE_CACHE }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache ./tmp/*
        uses: actions/cache@v2
        with:
          path: ./tmp
          key: ${{ runner.os }}-build-${{ env.TMP_CACHE }}-${{ hashFiles('./tmp/*') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.TMP_CACHE }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache Python installation
        uses: actions/cache@v2
        with:
          path: ${{ env.PYENV_PATH }}
          key: ${{ runner.os }}-build-python${{ env.PYTHON_VERSION }}-${{ hashFiles("$PYENV_PATH") }}
          restore-keys: |
            ${{ runner.os }}-build-python${{ env.PYTHON_VERSION }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: gabrielfalcao/pyenv-action@v7
        with:
          default: ${{ env.PYTHON_VERSION }}
          command: pip install -r ./bin/requirements.txt

      - name: Grant Gradle wrapper (gradlew) sufficient permissions
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew build --info

      - name: Run integration tests
        run: ./bin/integration_tests.py
