name: Unit and Integration Tests

on:
  push:
    paths:
      - '.github/workflows/unit-and-integration-tests.yml'
      - 'bin/**'
      - '!bin/api_tests.py'
      - '!bin/pgadmin.py'
      - '!bin/run.py'
      - 'src/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'settings.gradle'

env:
  GRADLE_CACHE: 'cache-gradle'
  TMP_CACHE: 'cache-tmp'

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ env.GRADLE_CACHE }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.GRADLE_CACHE }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64

      - name: Grant Gradle wrapper (gradlew) sufficient permissions
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew build --info

      - name: Run unit tests
        run: ./gradlew test --info

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ env.GRADLE_CACHE }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.GRADLE_CACHE }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache ./tmp/*
        uses: actions/cache@v2
        with:
          path: ./tmp
          key: ${{ runner.os }}-build-${{ env.TMP_CACHE }}-${{ hashFiles('./tmp/*') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.TMP_CACHE }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64

      - name: Install Python requirements
        run: |
          sudo python3 -m pip install -U pip
          sudo python3 -m pip install -U setuptools
          pip3 install -r ./bin/requirements.txt

      - name: Grant Gradle wrapper (gradlew) sufficient permissions
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew build --info

      - name: Run integration tests
        run: |
          # Set required envars
          export POSTGRES_URL='jdbc:postgresql://localhost:5432'
          export POSTGRES_DB='ggbot'
          export POSTGRES_USER='postgres'
          export POSTGRES_PASSWORD="$(xxd -l 16 -c 16 -p < /dev/random)"

          ./bin/integration_tests.py
